### PR TITLE
template reordering and ambiguity clarification

### PR DESCRIPTION
**Pull request by tpajenkamp**
- Helpers.hpp needed some templates to be reordered.
- Function range() from Helpers.hpp was called in an ambiguous way
  on several occurances.

Project did not compile on my machine (Ubuntu 14.04.3 LTS, g++ 4.8.4, Boost 1.54). The changes above where necessary to make it work.

### CODE REVIEW

**Comment by xavigonzalvo** [comment]
Have you tried this? https://github.com/xavigonzalvo/rnnlib

**Comment by tpajenkamp** [comment]
It is solely based on the code posted on sourceforge (http://sourceforge.net/projects/rnnl/), isn't it? I want to test the regression feature which does not work with that version, as far as I can tell.

**Comment by xavigonzalvo** [comment]
Ah ok! Yes it is.

**Comment by sehe** [comment]
Ah. We fixed mostly the same issues in mostly the same way. https://github.com/meierue/RNNLIB/pull/2

You missed the unqualified ::equal that also prevented successful compilation on my Ubuntu 15.10

Also, I think the fix to `indices` is incorrect in this pull request (it needs to be an unsigned type).

Finally, my pull request has the changes nicely split out into separate commits.

(not posting this as a critique; posting it to save time for others reviewing the differences)

Cheers!

**Comment by tpajenkamp** [comment]
Thanks for the comment. The fixes worked on my machine and I assumed the function signature was correct, but I guess you are right.

**Pull request closed without merging**
